on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      os-deployment_target:
        required: true
        type: string
      compiler-family:
        required: true
        type: string
      compiler-version:
        required: true
        type: string
      compiler-CC:
        required: true
        type: string
      compiler-CXX:
        required: true
        type: string
      flavor:
        required: true
        type: string
      ECO:
        type: string
    secrets:
      CODECOV_TOKEN:

env:
  RPUU_DST: ${{ github.workspace }}/raw-camera-samples/raw.pixls.us-unique
  COVERAGE_REPORT_PREFIX: rawspeed-coverage # relative to the workspace!

jobs:
  macOS:
    name: ${{ inputs.compiler-family }}.${{ inputs.compiler-version }}.targeting.OSX.${{ inputs.os-deployment_target }}.${{ inputs.flavor }}
    timeout-minutes: 10
    runs-on: ${{ inputs.os }}
    steps:
      - name: Fetch/Checkout RawSpeed git repo
        timeout-minutes: 1
        uses: actions/checkout@v3
        with:
          path: 'rawspeed'
          fetch-depth: 1
      - name: Install Base Dependencies
        timeout-minutes: 3
        env:
          SRC_DIR: ${{ github.workspace }}/rawspeed
        run: |
          set -xe
          brew update > /dev/null || true
          brew tap Homebrew/bundle
          cd "${SRC_DIR}/.ci/"
          brew bundle --verbose
      - name: Configure
        timeout-minutes: 4
        env:
          DEVELOPER_DIR: /Applications/Xcode_${{ inputs.compiler-version }}.app/Contents/Developer
          MACOSX_DEPLOYMENT_TARGET: ${{ inputs.os-deployment_target }}
          CC: ${{ inputs.compiler-CC }}
          CXX: ${{ inputs.compiler-CXX }}
          CFLAGS: -mmacosx-version-min=${{ inputs.os-deployment_target }}
          CXXFLAGS: -mmacosx-version-min=${{ inputs.os-deployment_target }}
          SRC_DIR: ${{ github.workspace }}/rawspeed
          BUILD_DIR: ${{ github.workspace }}/rawspeed-build
          INSTALL_PREFIX: ${{ github.workspace }}/rawspeed-install
          ECO: ${{ inputs.ECO }} -DALLOW_DOWNLOADING_GOOGLETEST=ON -DALLOW_DOWNLOADING_GOOGLEBENCHMARK=ON -DWITH_OPENMP=OFF
          FLAVOR: ${{ inputs.flavor }}
          TARGET: configure
        run: |
          set -xe
          if [[ "$MACOSX_DEPLOYMENT_TARGET" == "10.7" ]]; then
            export CXXFLAGS="$CXXFLAGS -stdlib=libc++"
          fi
          cmake -E make_directory "${BUILD_DIR}"
          cmake -E make_directory "${INSTALL_PREFIX}"
          "${SRC_DIR}/.ci/ci-script.sh"
      - name: Build
        timeout-minutes: 7
        env:
          SRC_DIR: ${{ github.workspace }}/rawspeed
          BUILD_DIR: ${{ github.workspace }}/rawspeed-build
          INSTALL_PREFIX: ${{ github.workspace }}/rawspeed-install
          TARGET: build
        run: |
          set -xe
          "${SRC_DIR}/.ci/ci-script.sh"
      - name: Test (unit tests)
        timeout-minutes: 1
        env:
          SRC_DIR: ${{ github.workspace }}/rawspeed
          BUILD_DIR: ${{ github.workspace }}/rawspeed-build
          INSTALL_PREFIX: ${{ github.workspace }}/rawspeed-install
          TARGET: test
        run: |
          set -xe
          "${SRC_DIR}/.ci/ci-script.sh"
      - name: Collect source coverage data (unit tests)
        timeout-minutes: 1
        if: inputs.flavor == 'Coverage'
        env:
          SRC_DIR: ${{ github.workspace }}/rawspeed
          BUILD_DIR: ${{ github.workspace }}/rawspeed-build
          COVERAGE_REPORT_PREFIX: ${{ github.workspace }}/${{ env.COVERAGE_REPORT_PREFIX }}/macOS
          INSTALL_PREFIX: ${{ github.workspace }}/rawspeed-install
          TARGET: coverage
        run: |
          set -xe
          "${SRC_DIR}/.ci/ci-script.sh"
          mkdir -p "${COVERAGE_REPORT_PREFIX}"
          mv "${BUILD_DIR}/gcov-reports-unittest" "${COVERAGE_REPORT_PREFIX}/unittests"
      - name: Upload coverage to Codecov (unit tests)
        timeout-minutes: 1
        if: inputs.flavor == 'Coverage'
        uses: codecov/codecov-action@v3
        env:
          OS: macOS
          ARCH: x86_64
          CXX: AppleXcode
          JOB_NAME: ${{ inputs.os }}.${{ inputs.compiler-family }}.${{ inputs.flavor }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          env_vars: OS,ARCH,CXX
          flags: macOS,unittests
          name: ${{ env.JOB_NAME }}.Unittests
          root_dir: ${{ github.workspace }}/rawspeed
          directory: ${{ github.workspace }}/${{ env.COVERAGE_REPORT_PREFIX }}/macOS/unittests
          fail_ci_if_error: true
      - name: Test (benchmarks)
        timeout-minutes: 1
        env:
          SRC_DIR: ${{ github.workspace }}/rawspeed
          BUILD_DIR: ${{ github.workspace }}/rawspeed-build
          INSTALL_PREFIX: ${{ github.workspace }}/rawspeed-install
          TARGET: test_benchmarks
        run: |
          set -xe
          "${SRC_DIR}/.ci/ci-script.sh"
      - name: Collect source coverage data (benchmarks)
        timeout-minutes: 1
        if: inputs.flavor == 'Coverage'
        env:
          SRC_DIR: ${{ github.workspace }}/rawspeed
          BUILD_DIR: ${{ github.workspace }}/rawspeed-build
          COVERAGE_REPORT_PREFIX: ${{ github.workspace }}/${{ env.COVERAGE_REPORT_PREFIX }}/macOS
          INSTALL_PREFIX: ${{ github.workspace }}/rawspeed-install
          TARGET: coverage_benchmarks
        run: |
          set -xe
          "${SRC_DIR}/.ci/ci-script.sh"
          mkdir -p "${COVERAGE_REPORT_PREFIX}"
          mv "${BUILD_DIR}/gcov-reports-benchmarks" "${COVERAGE_REPORT_PREFIX}/benchmarks"
      - name: Upload coverage to Codecov (benchmarks)
        timeout-minutes: 1
        if: inputs.flavor == 'Coverage'
        uses: codecov/codecov-action@v3
        env:
          OS: macOS
          ARCH: x86_64
          CXX: AppleXcode
          JOB_NAME: ${{ inputs.os }}.${{ inputs.compiler-family }}.${{ inputs.flavor }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          env_vars: OS,ARCH,CXX
          flags: macOS,benchmarks
          name: ${{ env.JOB_NAME }}.Benchmarks
          root_dir: ${{ github.workspace }}/rawspeed
          directory: ${{ github.workspace }}/${{ env.COVERAGE_REPORT_PREFIX }}/macOS/benchmarks
          fail_ci_if_error: true
      - name: Install
        timeout-minutes: 1
        env:
          SRC_DIR: ${{ github.workspace }}/rawspeed
          BUILD_DIR: ${{ github.workspace }}/rawspeed-build
          INSTALL_PREFIX: ${{ github.workspace }}/rawspeed-install
          TARGET: install
        run: |
          set -xe
          "${SRC_DIR}/.ci/ci-script.sh"
